version: "3.8"

services:
  db:
    image: mysql:8
    container_name: homeeats-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeeatsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: homeeats-backend
    volumes:
      - ..:/workspace:cached
    ports:
      - "3400:3400"
    env_file:
      - ../.env
    depends_on:
      - db
    command: npm run dev

volumes:
  mysql_data: