version: "3.8"

services:
  db:
    image: mysql:8
    container_name: homeeats-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeeatsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../db/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: homeeats-backend
    volumes:
      - ..:/workspace:cached
    ports:
      - "3500:3500"
    env_file:
      - ../.env
    depends_on:
      - db
    command: npm run dev

volumes:
  mysql_data:
